import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex justify-center border-b bg-spruce-green h-14">
          <nav className="p-4 w-full max-w-3xl text-snow-white">
            <ul className="flex flex-row gap-8">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/keyboard-navigation">Keyboard navigation</Link>
              </li>
              <li>
                <Link href="/screen-reader">Screen reader</Link>
              </li>
            </ul>
          </nav>
        </header>
        <div className="flex min-h-[calc(100vh-3.5rem)] items-center justify-center bg-dark-bark font-sans">
          <main className="flex min-h-[calc(100vh-3.5rem)] w-full max-w-3xl flex-col items-center justify-between py-16 px-16 bg-light-bark sm:items-start">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
